#!/usr/bin/env bash

set -eu

archive=wn3.1.dict.tar.gz

wget -O $archive http://wordnetcode.princeton.edu/$archive
tar xvf $archive

regex="^[0-9]{8}\s[0-9]{2}\s[a-z]\s[0-9]{2}\s[a-zA-Z]*\s"
egrep -o $regex dict/data.adj | cut -d ' ' -f 5 > unapproved-adjectives
egrep -o $regex dict/data.noun | cut -d ' ' -f 5 > unapproved-nouns

rm -rf $archive dict/
